baseURL = "https://Bob-ho-z.github.io/"
title = "He Zhan Bo    Bob "

theme = "hugo-coder"

languageCode = "en-us"
defaultContentLanguage = "en"

paginate = 20

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "He Zhan Bo"
    description = "Bob he's personal website"
    keywords = "blog,developer,personal"
    info = "a  CUHK Computer Science year 3 student"
    avatarURL = "/images/avatar.jpg"
    #gravatar = "john.doe@example.com"
    footerContent = "Welcome to my website."

    dateFormat = "January 2, 2006"

    hideFooter = false
    hideCredits = false
    hideCopyright = false


    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorScheme = "dark"

    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    customCSS = []

    # Custom SCSS
    customSCSS = []

    # Custom JS
    customJS = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
#[params.fathomAnalytics]
  #  siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    #serverURL = "analytics.example.com"

# If you want to use plausible(https://plausible.io) for analytics, add this section
#[params.plausibleAnalytics]
    #domain = "example.com"
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
  #  serverURL = "analytics.example.com"

# If you want to use goatcounter(https://goatcounter.com) for analytics, add this section
#[params.goatCounter]
  #  code = "code"

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
#[params.cloudflare]
    #token = "token"

#[taxonomies]
  #category = "categories"
  #series = "series"
  #tag = "tags"
  #author = "authors"

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/Bob-ho-z/"
#[[params.social]]
  #  name = "Gitlab"
  #  icon = "fa fa-gitlab"
  #  weight = 2
  #  url = "https://gitlab.com/johndoe/"
[[params.social]]
    name = "Telephone"
    icon = "fa fa-mobile-phone"
    weight = 3
    url = "tel:52264372"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/bob-he-3516591a5/"
[[params.social]]
    name = "Gmail"
    icon = "fa fa-envelope-o"
    weight = 5
    url = "mailto:hezhanbo1998@gmail.com"
#[[params.social]]
#    name = "RSS"
#    icon = "fa fa-rss"
#    weight = 6
#    url = "https://myhugosite.com/index.xml"
#    rel = "alternate"
#    type = "application/rss+xml"


[languages]
    [languages.en]
        languageName = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "/about-en/"

            [[languages.en.menu.main]]
            name = "Plan"
            weight = 2
            url = "/plan-en/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 3
            url = "/projects/"

            [[languages.en.menu.main]]
            name = "Resume"
            weight = 5
            url = "/he_zhanbo_bob_resume.pdf"


    [languages.ch]
        languageName = "中文"
        title = "何展博"

        [languages.ch.params]
            author = "何展博"
            info = "一個在中大讀計算機科學的大三學生"
            description = "何展博的個人網頁"
            keywords = "blog,desenvolvedor,pessoal"
            footerContent = "歡迎來到我的網站"

        [languages.ch.menu]

            [[languages.ch.menu.main]]
            name = "關於我"
            weight = 1
            url = "/about-ch/"

            [[languages.ch.menu.main]]
            name = "計劃"
            weight = 2
            url = "/plan-ch/"

            [[languages.ch.menu.main]]
            name = "項目"
            weight = 3
            url = "/Project/"

            [[languages.ch.menu.main]]
            name = "簡歷"
            weight = 5
            url = "/resume/"
